### ISSUE TITLE
scikit-learn == 0.21.0 not found 

### ISSUE THREAD

**Issue by Chainesh** [computervisioneng/object-tracking-yolov8-deep-sort#1]
ERROR: Could not find a version that satisfies the requirement scikit-learn==0.21.0 (from versions: 0.9, 0.10, 0.11, 0.12, 0.12.1, 0.13, 0.13.1, 0.14, 0.14.1, 0.15.0, 0.15.1, 0.15.2, 0.16.0, 0.16.1, 0.17, 0.17.1, 0.18, 0.18.1, 0.18.2, 0.19.0, 0.19.1, 0.19.2, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.20.4, 0.21.1, 0.21.2, 0.21.3, 0.22, 0.22.1, 0.22.2.post1, 0.23.0, 0.23.1, 0.23.2, 0.24.0, 0.24.1, 0.24.2, 1.0, 1.0.1, 1.0.2, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.2.0rc1, 1.2.0, 1.2.1)
ERROR: No matching distribution found for scikit-learn==0.21.0

python == 3.10

**Comment by Dipankar1997161** [comment]
do a thing, use this command
1. remove the "==" signs from the requirements.txt
2. python=3.10 -m pip install scikit-learn

this will ensure that you install scikit-learn for your respective python version. change the python=" " for the version you need.

If you have queries, you can ask further.
Have a good day
