### ISSUE TITLE
scikit-learn version in requirements.txt is wrong

### ISSUE THREAD

**Issue by hilariie** [computervisioneng/object-tracking-yolov8-deep-sort#4]
in requirement file, we have scikit-learn==0.21.0.

running pip install -r requirements.txt there's an error:

ERROR: Could not find a version that satisfies the requirement scikit-learn==0.21.0 (from versions: 0.9, 0.10, 0.11, 0.12, 0.12.1, 0.13, 0.13.1, 0.14, 0.14.1, 0.15.0, 0.15.1, 0.15.2, 0.16.0, 0.16.1, 0.17, 0.17.1, 0.18, 0.18.1, 0.18.2, 0.19.0, 0.19.1, 0.19.2, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.20.4, 0.21.1, 0.21.2, 0.21.3, 0.22, 0.22.1, 0.22.2.post1, 0.23.0, 0.23.1, 0.23.2, 0.24.0, 0.24.1, 0.24.2, 1.0, 1.0.1, 1.0.2, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.2.0rc1, 1.2.0, 1.2.1, 1.2.2)
ERROR: No matching distribution found for scikit-learn==0.21.0

**Comment by TrinhNhatTuyen** [comment]
Same issues when i used python 3.10, i tried with python 3.7 and successfully installed it.
