### ISSUE TITLE
ModuleNotFoundError: No module named 'deep_sort'

### ISSUE THREAD

**Issue by blizaga** [computervisioneng/object-tracking-yolov8-deep-sort#5]
I have cloned the repository of deep_sort but it always shows the message 'ModuleNotFoundError: No module named 'deep_sort'' 

![image](https://github.com/computervisioneng/object-tracking-yolov8-deep-sort/assets/54091450/6d6ff2b7-df23-4724-b3c7-cd767970c834)

**Comment by hilariie** [comment]
1. clone this object-tracking-yolov8-deep-sort repo
2. cd into object-tracking-yolov8-deep-sort
3. clone his fork of deep_sort after you've entered the object-tracking-yolov8-deep-sort directory. You must be in the directory for the code to work.

I think this should solve the problem

**Comment by blizaga** [comment]
thank youuu
